M48
; DRILL file KiCad 10.0.1 date 2026-05-13T16:15:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-13T16:15:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X137.575Y-67.95
X142.425Y-67.95
T2
X137.275Y-64.92
X142.725Y-64.92
M30
